name: ASP.NET Web API CI (Test)

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore all projects
        run: dotnet restore

      - name: Build API (builds dependencies automatically)
        run: |
          dotnet build CapstoneProject_BE/capstone_be.csproj \
            --configuration Release \
            --no-restore

      - name: Test
        run: |
          dotnet test FCTMS.Tests/FCTMS.Tests.csproj \
            --configuration Release \
            --no-build
  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest
    environment: Test

    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Docker ----
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0

      # ---- Azure ----
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name fctmscapstone \
            --resource-group capstoneResourceGroup \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0
